# .streamlit/secrets.toml

[connections.snowflake]
account = "on89866.central-india.azure"
user = "LTI10705536"
password = "Snowflake@123"
role = "ACC360_DEV_DE_ROLE"
warehouse = "ACC360_DEV_DE_WH"
database = "ACCOUNT360"
schema = "ACC360_DATALAKE"
client_session_keep_alive = true
